
platform :ios, ‘8.0’
use_frameworks!

target 'LSKitDemo' do
    
     pod 'LSKit', :path => ‘../‘
     pod 'SDWebImage'
     pod 'ReactiveCocoa'
     
     target 'LSKitDemoTests' do
         inherit! :search_paths
         
     end
     
end
